### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by pazz** [haberda/hassio_addons#46]
Is there a way to use Hassio's MariaDB container as database?
I remember having set this up at some point but forgot how it worked and cannot figure it out any more.

So what I'm asking is upon initial setup, when selecting the database backend under Mariadb/Postgres,
which IP/port do I need and how should I set up the Mariadb add on to make this work?

ATM, that other addon is set up to have a "nextcloud" database

```
databases:
  - homeassistant
  - nextcloud
logins:
  - username: homeassistant
    password: mypasswd
rights:
  - username: homeassistant
    database: nextcloud
  - username: homeassistant
    database: homeassistant
```

In the nextcloud setup web interface I get the following message (I've tried localhost:3306)

```
Error
Error while trying to create admin user: 
Failed to connect to the database: 
An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused
```
Any ideas?
